version: '3'
services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # Web Console
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
